/* 
	Turtle skin by Laszlo Molnar
	(C) 2011
*/
var DEBUG=false,UNDEF="undefined",OBJECT="object",NOLINK="javascript:void(0)";SHOCKWAVE_FLASH="Shockwave Flash";SHOCKWAVE_FLASH_AX="ShockwaveFlash.ShockwaveFlash";FLASH_MIME_TYPE="application/x-shockwave-flash";String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.startsWith=function(b){return this.indexOf(b)===0};String.prototype.endsWith=function(b){return this.substring(this.length-b.length)===b};
String.prototype.getExt=function(){var b=this.lastIndexOf(".");return b<=0||b>=this.length-1?"":this.substring(b+1).toLowerCase()};var htmlregex=[[/<br>/,"\n"],[/\&amp;/,"&"],[/\&lt;/,"<"],[/\&gt;/,">"],[/\&(m|n)dash;/,"-"],[/\&apos;/,"'"],[/\&quot;/,'"']];String.prototype.cleanupHTML=function(){for(var b=this,j=htmlregex.length-1;j>=0;j--)b=b.replace(new RegEx(htmlregex[j][0],"gi"),htmlregex[j][1]);return b};String.prototype.stripHTML=function(){return this.replace(/<\/?[^>]+>/gi,"")};
String.prototype.stripQuote=function(){return this.replace(/\"/gi,"&quot;")};String.prototype.appendSep=function(b,j){return(this.length?this+(j||" &middot; "):"")+b};String.prototype.rgb2hex=function(){if(this.charAt(0)==="#")return this;for(var b,j=this.match(/\d+/g),m="",t=0;t<j.length&&t<3;t++)b=parseInt(j[t]).toString(16),m+=(b.length<2?"0":"")+b;return"#"+m};
String.prototype.template=function(b){if(!b)return this;for(var j=this,m=0;m<b.length;m++)j=j.replace(RegExp("\\{"+m+"\\}","gi"),b[m]);return j};Math.minMax=function(b,j,m){return $.isNaN(j)?b:j<b?b:j>m?m:j};var _logel,_logover=false,_lastlog,_lastcnt=1;
log=function(b){DEBUG&&!_logover&&(_logel||(_logel=$('<div id="log" style="position:fixed;left:0;top:0;width:200px;bottom:0;overflow:auto;padding:10px;background-color:rgba(0,0,0,0.5);color:#fff;font-size:15px;z-index:99999"></div>').hover(function(){_logover=true},function(){_logover=false}).appendTo("body")),b===_lastlog?_logel.children(":first").empty().html(_lastlog+" ("+ ++_lastcnt+")"):($('<div style="height:2em;overflow:hidden;">'+b+"</div>").prependTo(_logel),_lastlog=b,_lastcnt=1))};
checkFlash=function(b){var j=navigator,m=[1,0,0],t,b=b?b.split("."):[0,0,0];if(typeof j.plugins!=UNDEF&&typeof j.plugins[SHOCKWAVE_FLASH]==OBJECT){if((t=j.plugins[SHOCKWAVE_FLASH].description)&&!(typeof j.mimeTypes!=UNDEF&&j.mimeTypes[FLASH_MIME_TYPE]&&!j.mimeTypes[FLASH_MIME_TYPE].enabledPlugin))t=t.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),m[0]=parseInt(t.replace(/^(.*)\..*$/,"$1"),10),m[1]=parseInt(t.replace(/^.*\.(.*)\s.*$/,"$1"),10),m[2]=/[a-zA-Z]/.test(t)?parseInt(t.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),
10):0}else if(typeof window.ActiveXObject!=UNDEF)try{var J=new ActiveXObject(SHOCKWAVE_FLASH_AX);if(J&&typeof J.GetVariable!=UNDEF&&(t=J.GetVariable("$version")))t=t.split(" ")[1].split(","),m[0]=parseInt(t[0],10),m[1]=parseInt(t[1],10),m[2]=parseInt(t[2],10)}catch(a){}return m[0]>b[0]||m[0]==b[0]&&m[1]>b[1]||m[0]==b[0]&&m[1]==b[1]&&m[2]>=b[2]};
(function(b){b.fn.logEvents=function(a){var f=(a||"mousedown,mouseup,mouseover,mouseout,mousewheel,dragstart,click,blur,focus,load,unload,reset,submit,change,abort,cut,copy,paste,selection,drag,drop,orientationchange,touchstart,touchmove,touchend,touchcancel,gesturestart,gesturechange,gestureend").split(",");return this.each(function(){for(var a=0;a<f.length;a++)b(this).bind(f[a],function(a){a.target.id!=="log"&&log(a.type+' <span style="padding:0 4px;font-size:0.8em;background-color:#000;border-radius:4px;"><b>'+
a.target.nodeName.toLowerCase()+"</b>"+(a.target.id?":"+a.target.id:"")+"</span>"+(a.relatedTarget?' <span style="padding:0 4px;font-size:0.8em;background-color:#800;border-radius:4px;"><b>'+a.relatedTarget.nodeName.toLowerCase()+"</b>"+(a.relatedTarget.id?":"+a.relatedTarget.id:"")+"</span>":""));return true})})};b.fn.trackCss=function(a,f,c){var c=c||20,i=new Date;return this.each(function(){var g=b(this),h=function(a){var b=new Date-i;log(b+"&nbsp;::&nbsp;"+a+" = "+g.css(a));b>f&&clearInterval(k)},
k=setInterval(function(){if(b.isArray(a))for(var c=0;c<a.length;c++)h(a[c]);else h(a)},c)})};b.fn.readData=function(a,f){if(a==null||f==null)return this;var f=f.split(","),c,i=f.length,g;return this.each(function(){for(c=0;c<i;c++)if((g=b(this).data(f[c]))!=null)a[f[c]]=g})};b.extend(b.support,{orientation:"orientation"in window,touch:"ontouchend"in document,cssTransitions:"WebKitTransitionEvent"in window,cssTable:!b.browser.msie||b.browser.version>=8,cssFilter:b.browser.msie&&b.browser.version<=
8,flash:checkFlash("9.0.0")});b.extend(jQuery.easing,{easeOutBack:function(a,b,c,i,g,h){h==null&&(h=1.70158);return i*((b=b/g-1)*b*((h+1)*b+h)+1)+c},easeOutCubic:function(a,b,c,i,g){return i*((b=b/g-1)*b*b+1)+c}});b.fn.showin=function(){return this.each(function(){b(this).css("display","inline-block")})};b.fn.getDim=function(){var a=b(this).eq(0),f={width:a.width(),height:a.height()};if((f.width===0||f.height===0)&&a.css("display")==="none"){var c=a.css("position"),i=a.css("left");a.css({position:"absolute",
left:"-10000px",display:"block"});f.width=a.width();f.height=a.height();a.css({display:"none",position:c,left:i})}return f};var j=["DOMMouseScroll","mousewheel"],m=function(a){var f=a||window.event,c=[].slice.call(arguments,1),i=0,g=0,h=0,a=b.event.fix(f);a.type="mousewheel";a.wheelDelta&&(i=a.wheelDelta/120);a.detail&&(i=-a.detail/3);h=i;f.axis!==void 0&&f.axis===f.HORIZONTAL_AXIS&&(h=0,g=-1*i);f.wheelDeltaY!==void 0&&(h=f.wheelDeltaY/120);f.wheelDeltaX!==void 0&&(g=-1*f.wheelDeltaX/120);c.unshift(a,
i,g,h);return b.event.handle.apply(this,c)};b.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=j.length;a;)this.addEventListener(j[--a],m,false);else this.onmousewheel=m},teardown:function(){if(this.removeEventListener)for(var a=j.length;a;)this.removeEventListener(j[--a],m,false);else this.onmousewheel=null}};b.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}});
var t=function(a,b,c){if(arguments.length>1&&/^(string|number|boolean)$/.test(typeof b)){var i=new Date;i.setTime(i.getTime()+(typeof c!=="number"?1:c)*36E5);document.cookie=encodeURIComponent(a)+"="+String(b)+"; expires="+i.toGMTString()+"; path=/";return b}else if(a){a+="=";for(var i=document.cookie.split(";"),g,h=0;h<i.length;h++)if(g=i[h].trim(),g.indexOf(a)===0)return g=g.substring(a.length),/^(true|yes)$/.test(g)?true:/^(false|no)$/.test(g)?false:/^([\d.]+)$/.test(g)?parseFloat(g):g}return null};
(function(){function a(a){function c(a){var f=RegExp(b.map(a,encodeURIComponent).join("|"),"ig");return function(a){return a.replace(f,decodeURIComponent)}}a=b.extend({unescape:false},a||{});f.encoder=function(a){return a===true?function(a){return a}:typeof a=="string"&&(a=c(a.split("")))||typeof a=="function"?function(b){return a(encodeURIComponent(b))}:encodeURIComponent}(a.unescape)}var f={put:function(a,b){(b||window).location.hash=this.encoder(a)},get:function(a){a=(a||window).location.hash.replace(/^#/,
"");try{return b.browser.mozilla?a:decodeURIComponent(a)}catch(c){return a}},encoder:encodeURIComponent},c={id:"__jQuery_history",init:function(){var a='<iframe id="'+this.id+'" style="display:none" src="javascript:false;" />';b("body").prepend(a);return this},_document:function(){return b("#"+this.id)[0].contentWindow.document},put:function(a){var b=this._document();b.open();b.close();f.put(a,b)},get:function(){return f.get(this._document())}},i={base:{callback:void 0,type:void 0,check:function(){},
load:function(){},init:function(b,c){a(c);g.callback=b;g._options=c;g._init()},_init:function(){},_options:{}},timer:{_appState:void 0,_init:function(){var a=f.get();g._appState=a;g.callback(a);setInterval(g.check,100)},check:function(){var a=f.get();if(a!=g._appState)g._appState=a,g.callback(a)},load:function(a){if(a!=g._appState)f.put(a),g._appState=a,g.callback(a)}},iframeTimer:{_appState:void 0,_init:function(){var a=f.get();g._appState=a;c.init().put(a);g.callback(a);setInterval(g.check,100)},
check:function(){var a=c.get(),b=f.get();if(b!=a)b==g._appState?(g._appState=a,f.put(a),g.callback(a)):(g._appState=b,c.put(b),g.callback(b))},load:function(a){if(a!=g._appState)f.put(a),c.put(a),g._appState=a,g.callback(a)}},hashchangeEvent:{_init:function(){g.callback(f.get());b(window).bind("hashchange",g.check)},check:function(){g.callback(f.get())},load:function(a){f.put(a)}}},g=b.extend({},i.base);g.type=b.browser.msie&&(b.browser.version<8||document.documentMode<8)?"iframeTimer":"onhashchange"in
window?"hashchangeEvent":"timer";b.extend(g,i[g.type]);b.history=g})();b.fn.addScroll=function(a){a=b.extend({},b.fn.addScroll.defaults,a);return this.each(function(){var f,c=b(this),i=b(this).parent(),g,h,k,r,l,p,n,u,C=0,E,Q,ha,j,m,t,w;c.css({position:"absolute",width:i.width-20});i.css({overflow:"hidden"});i.css("position")!=="absolute"&&i.css({position:"relative"});g=b("<div>",{"class":a.upbtn}).appendTo(i);h=b("<div>",{"class":a.dnbtn}).appendTo(i);k=b("<div>",{"class":a.scbar}).appendTo(i);r=
b("<div>").appendTo(k);l=g.add(h).add(k);l.hide();var v=function(){return c.position().top},A=function(a){return Math.round((k.height()-4)*-(a==null?v():a)/p)+2},G=function(){return Math.max(Math.round((k.height()-4)*n/p),a.dragMinSize)},H=function(b){b==null&&(b=v());g.css({opacity:b?1:a.disabledOpacity});h.css({opacity:b===n-p?a.disabledOpacity:1})},T=function(){p=c.height();n=i.height();p<=n?(c.css({top:0}),l.hide()):(c.position().top<n-p&&c.css({top:n-p}),r.css({top:A(),height:G()}),l.show(),
H())},I=function(b){clearInterval(u);n>=p||(b=Math.minMax(n-p,b,0),r.stop(true,true).animate({top:A(b)},a.speed,a.effect),c.stop(true,true).animate({top:b},a.speed,a.effect,function(){H(b)}))};g.click(function(){I(v()+n);return false});h.click(function(){I(v()-n);return false});k.click(function(a){a.pageY<r.offset().top?I(v()+n):a.pageY>r.offset().top+r.height()&&I(v()-n);return false});a.enableMouseWheel&&c.mousewheel(function(b,c){c&&I(v()+a.wheelIncr*(c<0?-1:1));return false});var J=function(a){r.css({top:Math.minMax(1,
Math.round(a.pageY-r.data("my")),k.height()-r.height()-1)});c.css({top:-Math.max(Math.round((r.position().top-2)*p/(k.height()-4)),n-p)});H();return false},D=function(){b(document).unbind("mousemove",J).unbind("mouseup",D);return false};r.bind("mousedown",function(a){b(this).data("my",Math.round(a.pageY)-b(this).position().top);b(document).bind("mousemove",J).bind("mouseup",D);return false});var P=function(a){return C=a.touches&&a.touches.length>0?a.touches[0].clientY:a.clientY?a.clientY:C},V=function(){t+=
Math.round(m/20);var a=j+t;a>0||a<w?clearInterval(u):(c.css({top:a}),r.css({top:A(),height:G()}),m*=0.8,Math.abs(m)<10&&(m=0,clearInterval(u)))},K=function(a){if(a=P(a)-Q)c.data("dragOn",true),c.css({top:Math.minMax(w,E+a,0)}),r.css({top:A(),height:G()});return false},L=function(a){j=v();var a=P(a)-Q,f=(new Date).getTime()-ha;m=1E3*a/f;u=setInterval(V,50);b.support.touch?this.ontouchend=this.ontouchmove=null:b(document).unbind({mousemove:K,mouseup:L});setTimeout(function(){c.data("dragOn",false)},
20);return Math.abs(a)<4&&f<300},x=function(a){if(n>=p||(a.type==="touchstart"||a.type==="touchmove")&&(!a.touches||a.touches.length>1||c.is(":animated")))return true;clearInterval(u);te=a;E=v();Q=P(a);ha=(new Date).getTime();t=0;w=n-p;return b.support.touch?(b(a.target).closest("a").focus(),this.ontouchmove=K,this.ontouchend=L,true):(b(document).bind({mousemove:K,mouseup:L}),false)};b.support.touch?c[0].ontouchstart=x:c.bind("mousedown",x);b(window).resize(function(){clearTimeout(f);f=setTimeout(T,
50)});l.add(c).bind("selectstart",function(){return false});f=setTimeout(T,10);c.attr("role","scroll").data("dragOn",false).bind("adjust",T);(b.isFunction(a.enableKeyboard)||a.enableKeyboard)&&b(document).keydown(function(c){if(document.activeElement.nodeName==="INPUT"||b.isFunction(a.enableKeyboard)&&!a.enableKeyboard())return true;switch(c?c.keyCode:window.event.keyCode){case 33:return I(v()+n),false;case 34:return I(v()-n),false}return true})})};b.fn.addScroll.defaults={upbtn:"scrup",dnbtn:"scrdn",
scbar:"scrbar",dragMinSize:10,speed:250,effect:"easeOutBack",disabledOpacity:0.3,wheelIncr:50,enableKeyboard:true,enableMouseWheel:true};b.fn.scrollThumbs=function(a){a=b.extend({},b.fn.scrollThumbs.defaults,a);return this.each(function(){var f=b(this),c=b(this).parent(),i=0,g,h,k,r,l,p,n,u,C=b("<div>",{"class":a.scleft}).insertAfter(c),E=b("<div>",{"class":a.scright}).insertAfter(c),Q=function(b){b=b==null?f.position().left:b;C.css({opacity:b<0?1:a.disabledOpacity});E.css({opacity:c.width()<b+f.width()?
1:a.disabledOpacity})},j=function(g){var h=c.width(),n=f.width();if(h&&n&&!(h>=n||b.isNaN(g)))g>0?g=0:g<h-n&&(g=h-n),Q(g),f.stop(true,false).animate({left:g},a.speed,a.effect)};C.click(function(){j(f.position().left+c.width());return false});E.click(function(){j(f.position().left-c.width());return false});f.find("a").bind("setactive",function(){var g=b(this).parent()===f?b(this):b(this).parent(),h=g.position().left,g=g.outerWidth(true),n=Math.round(g*a.headRoom),i=f.position().left,u=c.width();f.find("a.active").removeClass("active");
b(this).addClass("active");if(!(u>f.width())){if(h>u-g-n-i)i=Math.max(u-g-n-h,u-f.width());else if(h<-i+n)i=-h+n;else return;j(i)}});a.enableMouseWheel&&f.mousewheel(function(a,b){b&&j(f.position().left+c.width()*(b<0?-1:1));return false});Q();var m=function(a){return i=a.touches&&a.touches.length>0?a.touches[0].clientX:a.clientX?a.clientX:i},t=function(){p+=Math.round(l/20);var a=r+p;a>0||a<n?clearInterval(u):(f.css({left:a}),l*=0.8,Math.abs(l)<10&&(l=0,clearInterval(u)))},F=function(a){if(a=m(a)-
h)f.data("dragOn",true),f.css({left:Math.minMax(n,g+a,0)});return false},w=function(a){r=f.position().left;var a=m(a)-h,c=(new Date).getTime()-k;l=1E3*a/c;u=setInterval(t,50);b.support.touch?this.ontouchend=this.ontouchmove=null:b(document).unbind({mousemove:F,mouseup:w});setTimeout(function(){f.data("dragOn",false)},20);return Math.abs(a)<4&&c<300},v=function(a){if((a.type==="touchstart"||a.type==="touchmove")&&(!a.touches||a.touches.length>1||f.is(":animated")))return true;clearInterval(u);te=a;
g=f.position().left;h=m(a);k=(new Date).getTime();p=0;n=c.width()-f.width();return b.support.touch?(b(a.target).closest("a").focus(),this.ontouchmove=F,this.ontouchend=w,true):(b(document).bind({mousemove:F,mouseup:w}),false)};b.support.touch?f[0].ontouchstart=v:f.bind("mousedown",v);f.attr("role","scroll").data("dragOn",false);f.add(C).add(E).bind("selectstart",function(a){a.preventDefault();return false})})};b.fn.scrollThumbs.defaults={scleft:"scleft",scright:"scright",speed:1500,incr:100,effect:"easeOutBack",
headRoom:0.67,disabledOpacity:0.3,enableMouseWheel:true};b.fn.swipe=function(a,f){return this.each(function(){var c=b(this),i=0,g=0,h=0,k,r,l,p=function(a){return i=a.touches&&a.touches.length>0?a.touches[0].clientX:a.clientX?a.clientX:i},n=function(a){c.css({left:p(a)-g+k});return false},u=function(){return false},C=function(i){h=c.position().left;i=p(i)-g;b.support.touch?this.ontouchend=this.ontouchmove=null:b(document).unbind("mousemove",n).unbind("mouseup click",C);Math.abs(i)>40?(l=1E3*i/((new Date).getTime()-
r),c.animate({left:h+Math.round(l/2)},500,"easeOutCubic"),i<0?b.isFunction(a)&&a.call():b.isFunction(f)&&f.call()):(c.animate({left:k},200),c.trigger("click"));return false},E=function(a){if((a.type==="touchstart"||a.type==="touchmove")&&(!a.touches||a.touches.length>1||c.is(":animated")))return true;clearInterval(void 0);k=c.position().left;g=p(a);r=(new Date).getTime();return b.support.touch?(this.ontouchmove=n,this.ontouchend=C,true):(c.unbind("click"),c.click(u),b(document).bind("mousemove",n).bind("mouseup",
C),a.cancelBubble=true,false)};b.support.touch?this.ontouchstart=E:c.bind("dragstart",E);c.bind("dragcancel",function(){c.stop(true,false).animate({left:k},200);return false});c.bind("unswipe",function(){b.support.touch?this.ontouchstart=this.ontouchend=this.ontouchmove=null:(b.isFunction(c.noClick)&&c.unbind(u),b.isFunction(c.dragStart)&&c.unbind(E),b(document).unbind("mousemove",n).unbind("mouseup",C))})})};b.fn.alignTo=function(a,f){f=b.extend({},b.fn.alignTo.defaults,f);return b(this).each(function(){var c=
a.offset(),i=b(this).outerWidth(),g=b(this).outerHeight(),h=Math.round(c.left+(a.outerWidth()-i)/2),k=c.top-f.gap-g;k<0&&(k=Math.min(c.top+a.outerHeight()+f.gap,b(window).height()-g));h+i>b(window).width()?h=b(window).width()-g:h<0&&(h=0);b(this).css({position:"absolute",left:h,top:k})})};b.fn.alignTo.defaults={gap:5};b.fn.addHint=function(a,f){var f=b.extend({},b.fn.addHint.defaults,f),c,i=b("#"+f.id),g,h=false;i.length||(i=b("<div>",{"class":f.id,id:f.id}).hide().appendTo("body"));var k=function(){h=
false;clearTimeout(g);r()},r=function(){!h&&c&&c.stop(true,false).animate({opacity:0},200,function(){b(this).hide()})},l=function(a){var a=b(a.target),n=a.data("hint");if(n==null&&(a=a.parents([data=c]).eq(0),!a.length||!(n=a.data("hint"))))return true;c!=null&&(g=clearTimeout(g),c.stop().hide());n&&n.jquery?c=n.addClass(f.id):(c=i,c.html(n).hide());c.hover(function(){g=clearTimeout(g);h=true;c.stop(true,true).css({opacity:1}).show()},function(){g=clearTimeout(g);h=false;r()});c.alignTo(a).css({opacity:0}).show().animate({opacity:1},
200);b.support.touch&&(g=setTimeout(r,f.stay))};return this.each(function(){var c=a||b(this).attr("title");c&&(b(this).data("hint",c).removeAttr("title"),b(this).bind(b.support.touch?"touchstart":"focus mouseenter",l),b(this).bind("blur mouseleave",k))})};b.fn.addHint.defaults={id:"hint",stay:3E3};b.fn.popupBox=function(a){a=b.extend({},b.fn.popupBox.defaults,a);b("#"+a.id).remove();var f,c=b("<div>",{id:a.id}).appendTo("body"),i=b("<div>",{"class":"panel"}).appendTo(c);i.css({width:a.width}).append(this);
var g=function(){c.fadeOut(250,function(){b(this).remove()})};c.fadeIn(250,function(){f=setTimeout(g,a.length)});i.css({marginTop:Math.max(Math.round((b(window).height()-i.outerHeight())*0.4),0)}).hover(function(){f=clearTimeout(f);b(this).stop(true,false).css("opacity",1)},function(){f=setTimeout(g,a.length)});return this};b.fn.popupBox.defaults={id:"modal",width:200,length:500};b.fn.alertBox=function(a,f){b.isArray(a)||(f=a,a=null);f=b.extend({},b.fn.alertBox.defaults,f);b("#"+f.id).remove();var c=
b("<div>",{id:f.id}).appendTo("body"),i=b("<div>",{"class":"panel"}).appendTo(c),g,h;i.append(this);i.append(b("<a>",{"class":"close",href:NOLINK,text:" "}).click(function(){r();return false}));a&&(g=b("<div>",{"class":"buttons"}).appendTo(i));i.css({width:f.width});var k=function(a){if(document.activeElement.nodeName==="input"||b.isFunction(f.enableKeyboard)&&!f.enableKeyboard())return true;var c=a?a.keyCode:window.event.keyCode;if(a===27)r();else if(g){var a=g.find("a.active"),n=h.index(a);switch(c){case 13:case 10:if(b.isFunction(a[0].handler))return a[0].handler.call(),
r(),false;case 39:return l((n+1)%h.length),false;case 37:return l(n?n-1:h.length-1),false}}return true},r=function(){b(document).unbind("keydown",k);c.fadeOut(250,function(){b(this).remove()})},l=function(a){h.each(function(c){b(this).toggleClass("active",c===a)})};if(a&&a.length){for(var p,n=0;n<a.length;n++){n&&g.append(" ");p=b("<a>",{href:NOLINK}).appendTo(g);p.html(a[n].t);if(b.isFunction(a[n].h))p[0].handler=a[n].h;p.click(function(){this.handler!=null&&this.handler.call();r();return false})}h=
g.children("a");h.last().addClass("active")}(b.isFunction(f.enableKeyboard)||f.enableKeyboard)&&b(document).keydown(k);c.fadeIn(250);i.css({marginTop:Math.max(Math.round((b(window).height()-i.outerHeight())*0.4),0)});return this};b.fn.alertBox.defaults={id:"modal",width:420,enableKeyboard:true};b.fn.equalHeight=function(){var a,f,c=0,i=0,g;return(g=b(this).length)<2?this:this.each(function(h){a=b(this);a.offset().top===c?(f=f?f.add(a):a,i=Math.max(i,a.height()),h===g-1&&i&&f.height(i)):(f&&i&&f.height(i),
f=a,i=a.height(),c=a.offset().top)})};b.fn.shareIt=function(a){var a=b.extend({},b.fn.shareIt.defaults,a),f=encodeURIComponent(a.useHash?window.location.href:window.location.href.split("#")[0]),c=encodeURIComponent(b("meta[name=title]").attr("content")||b("title").text()),i=encodeURIComponent(a.callTxt);encodeURIComponent(b("link[rel=img_src]").attr("content"));return this.each(function(){var g=b(this);this.nodeName==="a"&&g.attr("href",NOLINK);var h=b("<div>",{"class":a.id}).hide().appendTo("body");
location.protocol.startsWith("file:")&&!DEBUG?h.html(a.localWarning):(a.facebookLike&&h.append('<div class="likebtn"><iframe src="http://www.facebook.com/plugins/like.php?href='+f+"&amp;layout=button_count&amp;show_faces=false&amp;width=110&amp;action=like&amp;font=arial&amp;colorscheme="+a.likeBtnTheme+'&amp;height=20" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:110px; height:20px;" allowTransparency="true"></iframe></div>'),a.twitterTweet&&h.append('<div class="likebtn"><iframe allowtransparency="true" frameborder="0" scrolling="no" src="http://platform.twitter.com/widgets/tweet_button.html?url='+
f+"&text="+c+'" style="width:55px; height:20px;"></iframe></div>'),a.googlePlus&&gapi&&(h.append('<div class="likebtn" id="plusone"></div>'),gapi.plusone.render("plusone",{size:"medium",count:true})),a.tumblrBtn&&h.append('<div class="likebtn" id="tumblr"><a href="http://www.tumblr.com/share/photo?source='+f+"&caption="+c+'" title="Share on Tumblr" style="display:inline-block; text-indent:-9999px; overflow:hidden; width:81px; height:20px; background:url(http://platform.tumblr.com/v1/share_1.png) top left no-repeat transparent;">Tumblr</div>'),
a.facebook&&h.append('<a href="http://www.facebook.com/sharer.php?u='+f+"&t="+c+'" class="facebook">Facebook</a>'),a.twitter&&h.append('<a href="http://twitter.com/home?status='+i+": "+f+'" class="twitter">Twitter</a>'),a.digg&&h.append('<a href="http://digg.com/submit?url='+f+'" class="digg">Digg</a>'),a.delicious&&h.append('<a href="http://delicious.com/save?url='+f+"&title="+c+'&v=5" class="delicious">Delicious</a>'),a.myspace&&h.append('<a href="http://www.myspace.com/index.cfm?fuseaction=postto&t='+
c+"&u="+f+'&l=3" class="myspace">MySpace</a>'),a.stumbleupon&&h.append('<a href="http://www.stumbleupon.com/submit?url='+f+"&title="+c+'" class="stumbleupon">StumbleUpon</a>'),a.reddit&&h.append('<a href="http://www.reddit.com/submit?url='+f+'" class="reddit">Reddit</a>'),h.children("a").attr("target","_blank"),a.email&&h.append('<a href="mailto:?subject='+i+"&body="+c+"%0D%0A"+f+'" class="email">Email</a>'));g.addHint(h)})};b.fn.shareIt.defaults={id:"shares",useHash:true,likeBtnTheme:"light",facebookLike:true,
twitterTweet:true,googlePlus:true,tumblrBtn:true,facebook:true,twitter:true,digg:true,delicious:true,myspace:true,stumbleupon:true,reddit:true,email:true,callTxt:"Found this page",localWarning:"Can't share local albums. Please upload your album first!"};b.fn.addPlayer=function(a){var a=b.extend({},b.fn.addPlayer.defaults,a),f={flashVideo:".flv.3gp.3g2",video:".mp4.mov.f4v",html5Video:".ogv.webm",qtVideo:".qt.mpg.mpeg.mpe",wmVideo:".avi.wmv.asf.asx.wvx.mkv",audio:".mp3.aac.m4a",html5audio:".ogg.wav.ram.rm"},
c=0,i=a.resPath?a.resPath+"/":"",g=function(a){var b="",c;for(c in a)b+='<param name="'+c+'" value="'+a[c]+'">';return b},h=function(a){var c=b(a.target);c&&(b.browser.msie?(c.hide(),function(){if(c.readyState==4){if(c){for(var a in c)typeof c[a]==="function"&&(c[a]=null);c.remove()}}else setTimeout(arguments.callee,10)}()):c.remove())},k=function(f,h,k,r,l,p){var j="media"+c++,m=a.swf===b.fn.addPlayer.defaults.swf?24:0;f.addClass("flplayer").css({width:k,height:r+m});h="netstreambasepath="+encodeURIComponent(window.location.href.split("#")[0])+
"&id="+j+"&file="+encodeURIComponent(h)+"&image="+encodeURIComponent(l)+(p&&p.length?"&folder="+encodeURIComponent(p):"")+"&autostart="+a.auto+"&loop="+a.loop+"&screencolor="+encodeURIComponent(a.bgcolor)+"&controlbar.position=bottom";j='<object id="'+j+'" name="'+j+'" width="100%" height="100%" bgcolor="'+a.bgcolor+'" tabindex="0" ';b.browser.msie?(j+='classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">',j+=g({movie:i+a.swf})):j+='type="application/x-shockwave-flash" data="'+i+a.swf+'">';j+=g({allowfullscreen:true,
allowscriptaccess:"always",seamlesstabbing:true,wmode:"opaque",flashvars:h});return b(j).appendTo(f)},r=function(f,g,h,i){var k="em"+c++;f.addClass("emplayer");return b('<embed class="otherplayer" id="'+k+'" src="'+g+'" autostart="'+a.auto+'" loop="'+a.loop+'" width="'+h+'" height="'+i+'">').appendTo(f)},l=function(f,g,h,i,k,p){if((p=p!==UNDEF&&p)&&!Modernizr.audio||!p&&!Modernizr.video)return r(f,g,h,i);f.addClass("h5player").css({width:h,height:i+j});var l="ht"+c++,j=30,f=b(p?"<audio>":"<video>",
{id:l,src:g,width:h,height:i,controls:true,preload:"auto",poster:k,autoplay:a.auto,loop:a.loop}).appendTo(f);b.isFunction(a.complete)&&f.bind("ended",a.complete);return f},p=function(f,h,i,k){var p="wm"+c++;f.addClass("wmplayer").css({width:i,height:k+64});i='<object id="'+p+'" width="'+i+'" height="'+(k+64)+'" '+(b.browser.msie?'classid="CLSID:6BF52A52-394A-11D3-B153-00C04F79FAA6">':'type="application/x-ms-wmp" data="'+h+'">');i+=g({URL:h,SendPlayStateChangeEvents:true,AutoStart:a.auto,StretchToFit:a.fit});
b.browser.msie||(i+="<a></a>");el=b(i).appendTo(f);b.isFunction(a.complete)&&el.bind("playStateChange",function(){a.complete.call(this)});return el};return this.each(function(){var i=b(this),u=null;i.readData(a,"file,folder,width,height,poster");if(a.file){var j;a:{j=a.file.getExt();if(j.length)for(var m in f)if(f[m].indexOf(j)>=0){j=m;break a}j=null}switch(j){case "flashVideo":if(!b.support.flash){i.append(a.flashInstall);break}case "video":if(b.support.flash){u=k(i,a.file,a.width,a.height,a.poster);
break}case "html5Video":u=l(i,a.file,a.width,a.height,a.poster);break;case "qtVideo":u=a.file;j=a.width;m=a.height;var t="qt"+c++;i.addClass("qtplayer").css({width:j,height:m+16});j='<object id="'+t+'" width="'+j+'" height="'+(m+16)+'" '+(b.browser.msie?'classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab#version=6,0,2,0">':'type="video/quicktime" data="'+u+'">');j+=g({src:u,autoplay:a.auto,scale:a.fit?"tofit":"1",enablejavascript:true,postdomevents:true});
i=b(j).appendTo(i);b.isFunction(a.complete)&&i.bind("qt_ended",a.complete);u=i;break;case "wmVideo":u=p(i,a.file,a.width,a.height);break;case "audio":if(b.support.flash){u=k(i,a.file,a.width,a.height,a.poster,a.folder);break}case "html5audio":u=l(i,a.file,a.width,a.height,a.poster,true);break;default:u=r(i,a.file,a.width,a.height)}u.bind("remove",h)}})};b.fn.addPlayer.defaults={complete:null,swf:"player.swf",width:640,height:480,bgcolor:"#000000",auto:false,loop:false,fit:true,poster:"",folder:"",
flashInstall:'<a href="http://get.adobe.com/flashplayer/">Get Adobe Flash Player!</a>'};b.fn.centerThis=function(a){a=b.extend({},b.fn.centerThis.defaults,a);return this.each(function(){var f=b(this),c=f.find(a.selector),i,g,h,k,j,l=a.marginLeft+a.padding;i=a.marginRight+a.padding;var p=a.marginTop+a.padding;k=a.marginBottom+a.padding;g=c.data("ow");h=c.data("oh");if(!g||!h)g=c.width(),h=c.height();(bw=c.data("bw"))||c.data("bw",bw=parseInt(c.css("border-top-width")));i=(f.width()||b("body").width())-
2*bw-l-i;f=(f.height()||b("body").height())-2*bw-p-k;if(c[0].nodeName==="IMG"&&a.fit&&(g>i||h>f||a.enlarge))k=Math.min(i/g,f/h),g=Math.round(g*k),h=Math.round(h*k);k=Math.round((i-g)/2)+l;j=Math.round((f-h)/2)+p;if(a.animate){if(a.preScale&&a.preScale!==1){var n=g*a.preScale,u=h*a.preScale;c.css({left:Math.round((i-n)/2)+l,top:Math.round((f-u)/2)+p,width:Math.round(n),height:Math.round(u)})}else a.init&&c.css({left:k,top:j});c.animate({left:k,top:j,width:g,height:h},{duration:a.speed,easing:a.effect,
complete:a.complete})}else c.css({left:k,top:j,width:g,height:h}),b.isFunction(a.complete)&&a.complete.call(this)})};b.fn.centerThis.defaults={selector:".main",speed:500,fit:true,enlarge:true,marginTop:0,marginBottom:0,marginLeft:0,marginRight:0,padding:0,init:false,animate:false,effect:"swing",complete:null};b.fn.setupShop=function(a){var a=b.extend({},b.fn.setupShop.defaults,a),f;b.fn.addInput=function(a,c,f,k){var j;return this.each(function(){j=b("<input>",{type:f||"text"}).appendTo(b(this));
a&&(j.attr("name",a),j.addClass(a));c&&j.val(c);k&&j.prop(k,k)})};b.fn.addSelect=function(a,c,h){return!a.length?this:this.each(function(){var k=b(this),k=b("<select>").appendTo(k);for(f=0;f<a.length;f++)k.append(b("<option>",{val:a[f].val,text:a[f].key+" ("+c+" "+a[f].val+")"}));b.isFunction(h)&&k.change(h)})};var c=function(a){var a=a.split("::"),b,c=[];for(f=0;f<a.length;f++)b=a[f].split("="),b.length>1&&c.push({key:b[0],val:b[1]});return c};return this.each(function(){var f=b(this),g,h;f.readData(a,
"gateway,id,currency,handling,options,file");if(!(a.id==null||a.options==null||a.file==null)){id=a.gateway=="paypal"?{form:"paypal",seller:"business",currency:"currency_code",title:"item_name",select:"item_number",price:"amount",copies:"add",shipprice:"shipping",handling:"handling_cart"}:{form:"google_checkout",currency:"item_currency_1",title:"item_name_1",select:"item_description_1",price:"item_price_1",copies:"item_quantity_1",shipmethod:"ship_method_name_1",shipprice:"ship_method_price_1",shipcurrency:"ship_method_currency_1"};
var k=c(a.options);a.id=a.id.replace("|","@");var j=function(){var a,b=g.children("select");g.length&&b.length&&(b=b.val().split("+"),q=g.children("[name=copies]").val()||1,(a=g.children("[name=total]"))&&a.val((b[0]*q).toFixed(2)),(a=h.children("[name="+id.price+"]"))&&a.val(b[0]),(a=h.children("[name="+id.copies+"]"))&&a.val(q),b.length>1&&(a=h.children("[name="+id.shipprice+"]"))&&a.val(b[1]),(a=h.children("[name="+id.select+"]"))&&a.val(g.find("option:selected").text()))};g=b("<form>",{name:"shopping",
method:"post"}).appendTo(f);g.addSelect(k,a.currency,j);g.append("x").addInput("copies",1);g.append("=").addInput("total",k[0].val.split("+")[0],"text","readonly");g.children("[name=copies]").css({width:"3em"}).change(j);g.children("[name=total]").css({width:"5em"});g.append(a.currency);a.gateway==="paypal"?(h=b("<form>",{name:id.form,target:a.target,action:"https://www.paypal.com/cgi-bin/webscr/",method:"post"}).appendTo(f),h.addInput("cmd","_cart","hidden"),h.addInput(id.copies,1,"hidden"),h.addInput(id.seller,
a.id,"hidden"),h.addInput(id.price,k[0].val.split("+")[0],"hidden"),h.addInput(id.currency,a.currency,"hidden"),a.shipping!=null&&h.addInput(id.shipprice,parseInt(a.shipping)||0,"hidden"),a.handling!=null&&h.addInput(id.handling,parseInt(a.handling)||0,"hidden"),h.addInput(id.title,a.file,"hidden"),h.addInput(id.select,k[0].key,"hidden"),h.append(b("<input>",{id:"shopAdd",type:"image",name:"submit",src:"https://www.paypal.com/en_US/i/btn/btn_cart_SM.gif",alt:"Add to Cart"})),f=b("<form>",{"class":"view",
name:"paypalview",target:a.target,action:"https://www.paypal.com/cgi-bin/webscr/",method:"post"}).appendTo(f),f.addInput("cmd","_cart","hidden"),f.addInput("display",1,"hidden"),f.addInput(id.seller,a.business,"hidden"),f.append(b("<input>",{id:"shopView",type:"image",name:"submit",src:"https://www.paypal.com/en_US/i/btn/btn_viewcart_SM.gif",alt:"View Cart"}))):a.gateway==="google"&&(j=a.id.match(/(\d+)/)[0],h=b("<form>",{name:id.form,target:a.target,action:"https://checkout.google.com/cws/v2/Merchant/"+
j+"/checkoutForm",method:"post","accept-charset":"utf-8"}).appendTo(f),h.addInput(id.title,a.file,"hidden"),h.addInput(id.select,k[0].key,"hidden"),h.addInput(id.copies,1,"hidden"),h.addInput(id.price,k[0].val.split("+")[0],"hidden"),h.addInput(id.currency,a.currency,"hidden"),a.shipping!=null&&(h.addInput(id.shipmethod,"normal","hidden"),h.addInput(id.shipprice,a.shipping,"hidden"),h.addInput(id.shipcurrency,a.currency,"hidden")),h.addInput("_charset_","","hidden"),h.append(b("<input>",{id:"shopAdd",
type:"image",name:"Google Checkout",alt:"Fast checkout through Google",src:"http://checkout.google.com/buttons/checkout.gif?merchant_id="+j+"&w=160&h=43&style=trans&variant=text&loc=en_US",height:43,width:160})));h.find("input[name=submit]").click(function(){window.open("",a.target,"width=840,height=600,scrollbars=yes,resizable=yes,menubar=no,toolbar=no,directories=no,status=no,copyhistory=no")})}})};b.fn.setupShop.defaults={target:"ShoppingCart",currency:"EUR",gateway:"paypal"};var J=function(a){if(a==
null)return null;return typeof a==="string"?(a=/^(-?[\d.]+),\s?(-?[\d.]+)$/.exec(a),new google.maps.LatLng(a[1],a[2])):new google.maps.LatLng(a[0],a[1])};b.fn.setupMap=function(a){if(google.maps==null)return this;var a=b.extend({},b.fn.setupMap.defaults,a),f=a.markerPath==null?{}:{icon:new google.maps.MarkerImage(a.markerPath,new google.maps.Size(17,24),new google.maps.Point(0,0),new google.maps.Point(8,24)),shadow:new google.maps.MarkerImage(a.markerPath,new google.maps.Size(28,24),new google.maps.Point(17,
0),new google.maps.Point(8,24)),zIndex:9999},c=a.markerPath==null?{}:{icon:new google.maps.MarkerImage(a.markerPath,new google.maps.Size(17,21),new google.maps.Point(45,3),new google.maps.Point(8,24)),shadow:new google.maps.MarkerImage(a.markerPath,new google.maps.Size(28,21),new google.maps.Point(62,3),new google.maps.Point(8,24))};return this.each(function(){var i=b(this),g,h,j,m;i.readData(a,"type,zoom,map,label,resPath,markers");i.data("fresh",true).bind("adjust",function(){b(this).width()&&b(this).height()&&
b(this).data("fresh")&&(google.maps.event.trigger(j,"resize"),j.setCenter(g),b(this).data("fresh",false))});if(a.markers&&a.markers.length&&a.curr!=null)g=a.markers[a.curr].map;else if(a.map)g=J(a.map),h=a.label;else return;m&&m.length&&m.remove();m=b("<div>").css({position:"absolute",top:"-9000px",width:i.width(),height:i.height()}).appendTo("body");setTimeout(function(){var l=new google.maps.Map(m[0],{zoom:a.zoom,center:g,mapTypeId:a.type.toLowerCase()});google.maps.event.addListener(l,"maptypeid_changed",
function(){b.fn.setupMap.defaults.type=l.getMapTypeId()});google.maps.event.addListener(l,"zoom_changed",function(){b.fn.setupMap.defaults.zoom=l.getZoom()});if(a.markers&&a.markers.length>1)for(var p,n,u=Math.min(a.curr+a.range,a.markers.length),t=Math.max(a.curr-a.range,0);t<u;t++)if(n=a.markers[t],p={position:n.map,map:l,title:n.label,zIndex:t},t==a.curr)p=new google.maps.Marker(b.extend(p,f));else{if(p=new google.maps.Marker(b.extend(p,c)),jQuery.isFunction(a.click)&&n.link)p.link=n.link,google.maps.event.addListener(p,
"click",function(){a.click.call(this)})}else p=new google.maps.Marker(b.extend({position:g,map:l,title:h},f));m.css({top:0}).appendTo(i);j=l},20)})};b.fn.setupMap.defaults={type:"roadmap",zoom:16,range:30};b.fn.turtleGallery=function(a,f,c){var a=b.extend({},b.fn.turtleGallery.defaults,a),f=b.extend({},b.fn.turtleGallery.texts,f),c=b.extend({},b.fn.turtleGallery.ids,c),i=a.skipIndex?b(a.helpgall.template(f.help)):b(a.help.template(f.help));if(!a.licensee&&location.protocol.startsWith("http")&&!t("ls")){var g=
a.resPath+"/logo.png";setTimeout(function(){img=b(new Image);img.load(function(){var a=b("<div>").css({background:"url("+g+") 10px top no-repeat",textAlign:"left",minHeight:"60px",paddingLeft:"90px"});a.html("<h3>Turtle skin<h3></h3><p>Unlicensed</p>");a.popupBox();t("ls",true)}).attr("src",g)},1E3)}for(var h="thumbsOn,infoOn,metaOn,mapOn,shopOn,shareOn,printOn,fitImage".split(","),j=function(b,c){location.protocol.startsWith("file")||t(b,c);a[b]=c},m,l=0;l<h.length;l++)if(m=t(h[l]))a[h[l]]=m;if(b.support.touch)a.preScale=
false;b.fn.setupMap.defaults.zoom=a.mapZoom;b.fn.setupMap.defaults.type=a.mapType;b.fn.setupMap.defaults.markerPath=a.markerPath;b.fn.addPlayer.defaults.bgcolor=b("body").css("background-color").rgb2hex();b.fn.addPlayer.defaults.fit=a.videoFit;b.fn.addPlayer.defaults.auto=a.videoAuto;b.fn.centerThis.defaults.fit=a.fitImage;b.fn.centerThis.defaults.animate=a.transitions;b.fn.centerThis.defaults.padding=a.fitPadding;b.fn.centerThis.defaults.enlarge=!a.fitShrinkonly;b.fn.centerThis.defaults.selector=
"."+c.main;for(l in a.shares)b.fn.shareIt.defaults[l]=a.shares[l];b.fn.shareIt.defaults.callTxt=f.checkOutThis;var p=function(b){var f=b.data(c.caption);return f?f.stripHTML():(b=b.closest("a"))?b.attr("href").replace(RegExp("^"+a.slides+"\\/"),""):""};return this.each(function(){var g=b(this).find("a"),h,m,l,t,r,R,S,F,w,v,A,G,H,T,I,ia,D,P,V,K,L,x=null,y=null,z=0,M,ja,ka=b(window).width(),la=b(window).height(),ma=[],ya=function(c){if(document.activeElement.nodeName==="INPUT"||b.isFunction(a.enableKeyboard)&&
!a.enableKeyboard()||b("#modal:visible").length)return true;c=c?c.keyCode:window.event.keyCode;if(c===112)i.alertBox({width:680});else if(h.is(":visible"))switch(c){case 106:case 179:M?N():W();break;case 109:a.infoOn||a.thumbsOn?(na(),oa()):(pa(),qa());break;case 107:a.fitImage?ra():sa();break;case 27:Y();break;case 103:case 36:B(0);break;case 37:Z();break;case 39:O();break;case 97:case 35:B(g.length-1);break;default:return true}else switch(c){case 13:case 10:B();break;case 103:case 36:z=0;U();break;
case 37:z=(z?z:g.length)-1;U();break;case 39:z=(z+1)%g.length;U();break;case 97:case 35:z=g.length-1;U();break;default:return true}return false},Y=function(){var c=b("[role=main]");if(h.is(":visible"))N(),a.skipIndex?window.location.href=a.uplink||"../":(c.length&&c.is(":hidden")&&(c.children().andSelf().css({visibility:"visible",display:"block"}),c.find(".folders>ul>li").equalHeight(),c.find("[role=scroll]").trigger("adjust")),a.transitions?h.fadeOut(a.speed):h.hide(),a.hash!=="no"&&b.history.load(""));
c.find("[role=scroll]").data("dragOn",false)},za=function(a){var b;if(a==null)b=z;else if(typeof a==="number")b=Math.minMax(0,a,g.length);else if((b=g.index(a))<0)b=P.index(a);return b},Aa=function(a){var b,c;for(b=0;b<g.length;b++)if((c=g.eq(b).attr("href"))&&c.substring(c.lastIndexOf("/")+1)===a)return b;return-1},ta=function(){var a=g.eq(z).attr("href");return a&&a.substr(a.lastIndexOf("/")+1)},U=function(){g.filter("."+c.active).removeClass(c.active);g.eq(z).addClass(c.active);P.eq(z).trigger("setactive")},
Z=function(){N();z?B(z-1):a.slideshowLoop?B(g.length-1):x.find("img."+c.main).trigger("dragcancel")},O=function(){if(z<g.length-1)da(),B(z+1);else if(a.slideshowLoop)da(),B(0);else if(a.askAtLast){N();x.find("img."+c.main).trigger("dragcancel");var h=Array({t:f.startOver,h:function(){B(0)}});a.uplink&&h.push({t:a.level>0?f.upOneLevel:f.backToHome,h:function(){window.location.href=a.uplink||"../"}});a.skipIndex||h.push({t:f.backToIndex,h:function(){Y()}});b("<h4>"+f.atLastPage+"</h4><p>"+f.atLastPageQuestion+
"</p>").alertBox(h)}},da=function(){M&&(clearInterval(M),M=setInterval(O,a.slideshowDelay))},W=function(){R.hide();S.showin();M=setInterval(O,a.slideshowDelay)},N=function(){S.hide();R.showin();M=clearInterval(M)},ua=function(){K||(t.stop(true,false).css({opacity:0.7}).fadeIn(500,function(){b.support.cssFilter&&t.css("filter","")}),L=setTimeout(function(){ea()},3E3))},ea=function(){K?L=setTimeout(function(){ea()},1E3):(L=clearTimeout(L),t.fadeOut(1E3))},na=function(){a.infoOn&&(F.hide(),w.showin(),
a.transitions?r.animate({bottom:-r.outerHeight()},500,function(){r.hide()}):r.css({bottom:-r.outerHeight()}).hide(),j("infoOn",false))},pa=function(){if(!a.infoOn){w.hide();F.showin();r.is(":hidden")&&r.show().css({bottom:-r.outerHeight()});var b=function(){r.children(c.map).trigger("adjust")};a.transitions?r.animate({bottom:0},500,b):(r.show().css({bottom:0}),b());j("infoOn",true)}},oa=function(){a.thumbsOn&&(v.hide(),A.showin(),a.transitions?l.animate({top:-D.outerHeight()-10},500):l.css({top:-D.outerHeight()-
10}),x&&a.fitFreespace&&x.centerThis({fit:a.fitImage,marginTop:0}),j("thumbsOn",false))},qa=function(){a.thumbsOn||(A.hide(),v.showin(),a.transitions?l.animate({top:0},500):l.css({top:0}),x&&a.fitFreespace&&x.centerThis({fit:a.fitImage,marginTop:D.outerHeight()}),j("thumbsOn",true))},X=function(){return a.fitFreespace&&l.position().top>=0?D.outerHeight()||0:0},ra=function(){G.hide();H.showin();x.centerThis({fit:false,marginTop:X()});j("fitImage",false)},sa=function(){H.hide();G.showin();x.centerThis({fit:true,
marginTop:X()});j("fitImage",true)},va=function(a){if(!(a<0||a>=g.length)){var f=g.eq(a).children("img").eq(0);!f.data(c.isvideo)&&!f.data(c.isother)&&!f.data("cached")&&(s=f.data(c.src))&&b("<img>").load(function(){f.data("cached",true)}).attr({src:s})}},aa=function(a){a.trigger("remove")},B=function(i){h.is(":hidden")&&(a.transitions?h.fadeIn(a.speed):h.show());i=za(i);if(!(i===z&&x)){var j,k=g.eq(i),l,p,k=k.children("img").eq(0);if(k.length){x&&(y&&y.length&&(y.stop().remove(),aa(y)),y=x,y.css({zIndex:0}),
y.find("."+c.main).trigger("unswipe").unbind("touchstart"),y.unmousewheel());(j=h.children("."+c.img).not(x)).length&&j.stop().remove();var r;x=b("<div>",{"class":c.img}).css({zIndex:1,display:"none"}).appendTo(h);m.css({opacity:0,display:"block"}).animate({opacity:1});z=i;U();if(k.data(c.isother)||!(l=k.data(c.src)))p=k.clone(),j=b("<div>",{"class":c.main+" "+c.other}),j.append(b("<a>",{href:k.data(c.link),target:"_blank"})),j.append(b("<p>",{text:f.clickToOpen})),j.children("a:first").append(p),
fa(j);else if(k.data(c.isvideo)||k.data(c.isaudio)){var t=M;t&&N();if(k.data(c.isvideo)){l=h.width()-40;var v=h.height()-40;j=k.data(c.width);r=k.data(c.height);if(j>l||r>v)l=Math.min(l/j,v/r),j*=l,r*=l}else j=Math.max(280,k.attr("width")||0),r=Math.max(128,k.attr("height")||0);l=b("<div>",{"class":c.main+" "+c.other}).css({width:j,height:r});el=l.addPlayer({complete:function(){t&&(O(),W())},file:k.data(c.link),resPath:a.resPath,poster:k.attr("src"),auto:a.videoAuto,fit:a.videoFit,width:j,height:r});
l.data("media",el);fa(l)}else p=b(new Image),j=k.data(c.width),r=k.data(c.height),p.addClass(c.main).load(function(){k.data("cached",true);fa(p)}).attr({src:l,width:j||"auto",height:r||"auto"}).data({ow:j,oh:r});Ba(k,i)}}},fa=function(f){if(a.transitions){if(m.stop(true,false).animate({opacity:0},{duration:100,complete:function(){b(this).hide()}}),y){var g=y;y.stop(true,false).animate({opacity:0},{duration:a.speed/2,complete:function(){g.remove();aa(g)}});y=null}}else m.hide(),y&&(aa(y),y.stop().remove());
var h=f[0].nodeName==="IMG";x.children().not("."+c.bottom).remove();x.append(f);a.rightClickProtect&&f.bind("contextmenu",function(a){a.preventDefault();return false});a.enableMouseWheel&&x.mousewheel(function(a,b){b>0?Z():O();return false});setTimeout(function(){b.support.touch?f.bind("touchstart",function(){ua()}):h&&f.click(function(){O()});f.swipe(function(){b(this).trigger("unswipe");O()},function(){b(this).trigger("unswipe");Z()})},a.speed/2);a.transitions?x.css({opacity:0,display:"block"}).animate({opacity:1},
{duration:a.speed,complete:b.browser.cssFilter?function(){x.css({filter:""})}:null}).centerThis({init:true,speed:Math.round(a.speed*0.75),marginTop:X(),preScale:h&&a.preScale,animate:h&&a.preScale&&a.preScale!=1,fit:h&&a.fitImage}):x.show().centerThis({init:true,marginTop:X(),fit:h&&a.fitImage});va(z+1);va(z-1);if(a.hash==="number")b.history.load(z+1);else if(a.hash==="fileName"){var i=ta();i&&b.history.load(i)}},Ba=function(h,i){r=b("<div>",{"class":c.bottom});var l=b("<div>",{"class":c.cont}).appendTo(r),
m=b("<nav>").appendTo(l),t,u;l.append('<div class="nr"><strong>'+(i+1)+"</strong> / "+g.length+"</div>");(t=h.data(c.caption))&&l.append(t);for(var v,y,w,C=[c.meta,c.map,c.shop,c.share,c.print,c.comment],A=0;A<C.length;A++)w=C[A],h.data(w)!=null&&(y=b("<div>",{"class":c.panel+" "+c[w]}).data("rel",w).appendTo(l),y.append(b("<div>",{"class":c.icon})),v=b("<a>",{href:NOLINK,"class":w+"-"+c.icon,text:" "}).appendTo(m),v.data("rel",w).addHint(f[w+"Btn"]||w),v.click(function(){var f=b(this).data("rel"),
g=l.children("."+f);o=g.is(":hidden");b(this).toggleClass(c.active,o);if(f===c.map){var h=function(){g.children("."+c.mapcont).trigger("adjust")};a.transitions?g.slideToggle("fast",h):(g.toggle(),setTimeout(h,50))}else a.transitions?g.slideToggle("fast"):g.toggle();j(f+"On",o)}));if(t=h.data(c.link))v=b("<a>",{href:t,"class":c.link+"-"+c.icon,target:"_blank",text:" "}).appendTo(m),v.addHint(h.data(c.isoriginal)?f.original:f.hiRes);a.shareOn&&(v=b("<a>",{href:t,"class":c.share+"-"+c.icon,target:"_blank",
text:" "}).appendTo(m),u=a.hash==="number"?z+1:ta(),setTimeout(function(){v.shareIt({hash:u})},a.speed));x.append(r);l.children("."+c.panel).each(function(){y=b(this);if((w=y.data("rel"))&&(t=h.data(w))!=null){if(w===c.map){var f=b("<div>",{"class":c.mapcont}).appendTo(y);a.mapAll?f.setupMap({click:function(){B(this.link)},markers:ma,curr:parseInt(h.data(c.mapid))}):f.setupMap({map:t,label:p(h)})}else w===c.shop?y.addClass("clearfix").setupShop({file:h.attr("src").replace("thumbs/",""),gateway:a.shopGateway,
id:a.shopId,currency:a.shopCurrency,handling:a.shopHandling,options:t}):y.append(t);a[w+"On"]?m.children("a."+w+"-icon").addClass(c.active):y.hide()}});m.html().length||m.remove();a.infoOn||r.hide()};if(g.length){(function(){if(a.header!=null){var g=b(a.header);if(g.length){var h=b("<div>",{"class":c.startBtn,text:" "}).appendTo(g),j=b("<div>",{"class":c.startTxt,text:f.startSlideshow}).appendTo(g);h.mouseenter(function(){j.stop(true,false).css({opacity:1}).hide().fadeIn(250)}).mouseleave(function(){j.stop(true,
false).fadeOut(500)}).click(function(){B();W();return false});h=g.find("."+c.parent+">a");if(h.length)a.uplink=h.attr("href");b("[role=main]").find("a."+c.help).click(function(){i.alertBox({width:680})})}}})();h=b("<div>",{"class":c.gallery}).appendTo("body");m=b("<div>",{"class":c.wait}).appendTo(h);l=b("<div>",{"class":c.navigation}).appendTo(h);D=function(h){var i,j,k,l,m=0;e=b("<div>",{"class":c.scrollbox}).appendTo(h);tc=b("<div>",{"class":"wrap"}).appendTo(e);re=RegExp("^"+a.slides+"\\/");nl=
'<span class="'+c.newItem+'">'+f.newItem+"</span>";d=Math.round((new Date).getTime()/864E5);tc=b("<ul>",{"class":c.cont}).appendTo(tc);g.each(function(f){h=b(this);k=h.find("img").eq(0);l=h.attr("href");k.length&&l&&(i=b("<a>",{href:NOLINK}).appendTo(b("<li>").appendTo(tc)),j=b("<img>").appendTo(i),k.data(c.src,l),k.attr("src").endsWith("/"+a.loadImg)?k.add(j).attr("src",a.thumbs+"/"+l.replace(re,"")):j.attr("src",k.attr("src")),h.add(i).addHint(h.attr("title")),a.markNewDays&&d-parseInt(k.data(c.modified)||
0)<=a.markNewDays&&h.add(i).append(nl),h.click(function(){if(b(this).parents("[role=scroll]").data("dragOn")===true)return false;!b(this).hasClass(c.active)&&x&&x.length&&(x.stop().remove(),aa(x));B(g.eq(f));return false}),i.click(function(){if(b(this).parents("[role=scroll]").data("dragOn")===true)return false;b(this).hasClass(c.active)||B(g.eq(f));b(this).trigger("active");return false}),m+=i.outerWidth(true))});tc.width(m).scrollThumbs({enableMouseWheel:a.enableMouseWheel});return e}(l);P=D.find(".cont a");
t=function(g){g=b("<nav>",{"class":"controls clearfix"}).appendTo(g);T=b("<a>",{"class":c.prev,title:f.previousPicture}).appendTo(g);T.click(function(){N();Z();return false});I=b("<a>",{"class":c.up,title:a.skipIndex?f.upOneLevel:f.backToIndex}).appendTo(g);I.click(function(){N();Y();return false});G=b("<a>",{"class":c.noresize,title:f.oneToOneSize}).appendTo(g);G.click(function(){ra();return false});H=b("<a>",{"class":c.resize,title:f.fitToScreen}).appendTo(g);H.click(function(){sa();return false});
a.fitImage?(H.hide(),G.showin()):(G.hide(),H.showin());F=b("<a>",{"class":c.hideInfo,title:f.hideInfo}).appendTo(g);F.click(function(){na();return false});w=b("<a>",{"class":c.showInfo,title:f.showInfo}).appendTo(g);w.click(function(){pa();return false});a.infoOn?(w.hide(),F.showin()):(F.hide(),w.showin());v=b("<a>",{"class":c.hideThumbs,title:f.hideThumbs}).appendTo(g);v.click(function(){oa();return false});A=b("<a>",{"class":c.showThumbs,title:f.showThumbs}).appendTo(g);A.click(function(){qa();
return false});a.thumbsOn?(A.hide(),v.showin()):(v.hide(),A.showin());R=b("<a>",{"class":c.play,title:f.startAutoplay}).appendTo(g);R.click(function(){W();return false});S=b("<a>",{"class":c.pause,title:f.stopAutoplay}).appendTo(g);S.click(function(){N();return false});a.slideshowAuto?(R.hide(),S.showin()):(S.hide(),R.showin());ia=b("<a>",{"class":c.next,title:f.nextPicture}).appendTo(g);ia.click(function(){da();O();return false});var h=0;g.children().each(function(){b(this).css("display")!=="none"&&
(h+=b(this).outerWidth())});g.width(h);g.children("a").addHint();return g}(l);a.thumbsOn||l.css("top",-D.outerHeight()-10);D.mouseenter(function(){ea();V=true}).mouseleave(function(){V=false});t.mouseenter(function(){K=true;b(this).stop(true,false).fadeTo(200,1)}).mouseleave(function(){K=false;b(this).stop(true,false).fadeTo(200,0.7)});var wa=0,xa=0;b.support.touch||h.mousemove(function(a){if(!V&&(wa-a.clientY||xa-a.clientX))ua(),xa=a.clientX,wa=a.clientY});if(a.mapAll){var ba,ca,ga;g.each(function(a){ba=
b(this).find("img:first");if(ba.length&&(ca=ba.data("map"))&&(ca=J(ca)))ga=p(ba),ma.push({map:ca,label:a+1+(ga?": "+ga.stripHTML():""),link:b(this)})})}!b.support.touch&&(b.isFunction(a.enableKeyboard)||a.enableKeyboard)&&b(document).keydown(ya);a.hash&&a.hash!=="no"&&b.history.init(function(c){c&&c.length?(c=a.hash==="number"?(parseInt(c)||1)-1:Aa(c),B(c),a.slideshowAuto=false):(Y(),b.browser.msie&&setTimeout(function(){b("[role=main]").show();b(".folders>ul>li").equalHeight();b("[role=scroll]").trigger("adjust")},
10))});U(z);a.slideshowAuto?(B(z),W()):a.skipIndex&&B(z);b(window).resize(function(){clearTimeout(ja);ja=setTimeout(function(){var c=b(window).width(),f=b(window).height();if(c!==ka||f!==la)x&&x.centerThis({fit:a.fitImage,marginTop:X()}),ka=c,la=f},100)})}})};b.fn.turtleGallery.defaults={hash:"fileName",resPath:"",relPath:"",level:0,skipIndex:false,speed:600,transitions:true,preScale:0.95,slideshowDelay:3E3,slideshowLoop:false,slideshowAuto:false,newDays:30,askAtLast:true,infoOn:true,thumbsOn:false,
fitImage:true,fitShrinkonly:true,fitFreespace:true,fitPadding:15,borderWidth:10,rightClickProtect:false,metaOn:false,mapOn:false,shopOn:false,shareOn:false,printOn:false,enableKeyboard:true,enableMouseWheel:true,numberLinks:false,videoAuto:true,videoFit:true,videoWidth:640,videoHeight:480,controlbarHeight:24,help:'<h2>{0}</h2><ul class="help index"><li><span>1</span>{1}</li><li><span>2</span>{2}</li><li><span>3</span>{3}</li><li><span>4</span>{4}</li></ul><hr><ul class="help gall"><li><span>1</span>{5}</li><li><span>2</span>{6}</li><li><span>3</span>{7}</li><li><span>4</span>{8}</li><li><span>5</span>{9}</li><li><span>6</span>{10}</li><li><span>7</span>{11}</li></ul><p>{12}</p>',
helpgall:'<h2>{0}</h2><ul class="help gall"><li><span>1</span>{5}</li><li><span>2</span>{1}</li><li><span>3</span>{7}</li><li><span>4</span>{8}</li><li><span>5</span>{9}</li><li><span>6</span>{10}</li><li><span>7</span>{11}</li></ul><p>{12}</p>'};b.fn.turtleGallery.texts={startSlideshow:"Start slideshow",close:"Close",atLastPage:"At last page",atLastPageQuestion:"Where to go next?",startOver:"Start over",backToHome:"Back to home",stop:"Stop",upOneLevel:"Up one level",backToIndex:"Back to index page",
previousPicture:"Previous picture",nextPicture:"Next picture",oneToOneSize:"1:1 size",fitToScreen:"Fit to screen",showInfo:"Show caption / info",hideInfo:"Hide caption / info",showThumbs:"Show thumbnails",hideThumbs:"Hide thumbnails",startAutoplay:"Start autoplay",stopAutoplay:"Stop autoplay",closeWindow:"Close window",clickToOpen:"Click to open this document with the associated viewer",download:"Download",original:"Original",hiRes:"Hi res.",metaBtn:"Photo data",metaLabel:"Display photograpic (Exif/Iptc) data",
mapBtn:"Map",mapLabel:"Show the photo location on map",shopBtn:"Buy",shopLabel:"Show options to buy this item",shareBtn:"Share",shareLabel:"Share this photo over social sites",help:"Using Turtle gallery,Up one level <em>Up arrow</em>,Share album over social sites,Start slideshow <em>Numpad *</em>,Author / Company info,Previous image <em>Left arrow</em>,Back to index page <em>Esc</em>,Toggle zoom (fit/1:1) <em>Numpad +</em>,Toggle info window <em>Numpad -</em>,Toggle thumbnail scoller,Start / Stop slideshow <em>Numpad *</em>,Next image <em>Right arrow</em>,Swipe for previous / next image".split(",")};
b.fn.turtleGallery.ids={gallery:"gallery",navigation:"navigation",scrollbox:"scrollbox",active:"active",parent:"parent",bottom:"bottom",img:"img",main:"main",video:"video",audio:"audio",other:"other",wait:"wait",cont:"cont",panel:"panel",icon:"icon",caption:"caption",meta:"meta",map:"map",mapcont:"mapcont",mapid:"mapid",shop:"shop",share:"share",print:"print",comment:"comment",link:"link",isoriginal:"isoriginal",width:"width",height:"height",src:"src",isvideo:"isvideo",isaudio:"isaudio",isother:"isother",
modified:"modified",startBtn:"startbtn",startTxt:"starttxt",prev:"prev",next:"next",up:"up",noresize:"noresize",resize:"resize",hideInfo:"hideinfo",showInfo:"showinfo",hideThumbs:"hidethumbs",showThumbs:"showthumbs",play:"play",pause:"pause",help:"helpbtn",newItem:"newlabel",showHint:"showhint"}})(jQuery);
